//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAHRO.WEB {
    
    
    public partial class AgencyDetails {
        
        /// <summary>
        /// ucEmp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAHRO.WEB.ctrlEmplyees ucEmp;
        
        /// <summary>
        /// ucAsc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAHRO.WEB.Controls.ctrlAssociates ucAsc;
        
        /// <summary>
        /// ucManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NAHRO.WEB.Controls.ctrlManagers ucManager;
    }
}
